// web/src/pages/Claim.vue
<template>
   <Layout>
    <form novalidate class="claim-form">
      <h1 class="claim-title">Claim Token</h1>
      <p>
        Please make sure to store this token safely, as only one token can be generated per project
        and you will not be able to claim it again.
      </p>


      <md-field>
        <label>Projectname</label>
        <md-select type="text" id="project" name="project" v-model="form.project" :disabled="sending" >
          <md-option
            v-for="project of projects"
            v-bind:key="project"
            :value="project"
          >
            {{ project }}
          </md-option>
        </md-select>
      </md-field>

      <md-field v-if="form.token">
        <label>Token</label>
        <md-input id="token" name="token" v-model="form.token" readonly />
      </md-field>

      <md-progress-bar md-mode="indeterminate" class="md-accent" v-if="sending" />
      <md-button class="md-button md-raised md-primary" :disabled="sending" @click="claim">Claim</md-button>

      <md-snackbar md-position="left" :md-duration="4000" :md-active.sync="showError" md-persistent>
        <span>{{ error }}</span>
        <md-button class="md-primary" @click="showError = false">Close</md-button>
      </md-snackbar>
    </form>
  </Layout>
</template>

<script>
import { validationMixin } from 'vuelidate'
import { required } from 'vuelidate/lib/validators'

import Layout from '@/components/Layout.vue'
import ProjectRepository from '@/repositories/ProjectRepository'

export default {
  name: 'Claim',
  mixins: [validationMixin],
  components: {
    Layout,
  },
  data() {
    return {
      form: {
        token: '',
        project: ''
      },
      projects: [],
      sending: false,
      error: '',
    }
  },
  async created() {
    document.title = "Claim Token | docat"
    this.projects = (await ProjectRepository.get()).map((project) => project.name)
  },
  validations: {
    form: {
      project: { required }
    }
  },
  methods: {
    async claim() {
      this.sending = true

      try {
        const msg = await ProjectRepository.claim(this.form.project)
        this.form.token = msg.token
      } catch(err) {
        // something went wrong while
        this.showError = true
        this.error = err
      }

      this.sending = false
    }
  }
}
</script>

<style scoped>
.claim-title {
  margin-bottom: 16px;
}

.claim-form {
  margin-top: 48px;
  padding-right: 16px;
  padding-left: 16px;
}
</style>

// web/src/pages/Claim.tsx
import { TextField } from '@mui/material'
import React, { useState } from 'react'
import DataSelect from '../components/DataSelect'
import PageLayout from '../components/PageLayout'
import StyledForm from '../components/StyledForm'
import { useMessageBanner } from '../data-providers/MessageBannerProvider'
import { useProjects } from '../data-providers/ProjectDataProvider'
import ProjectRepository from '../repositories/ProjectRepository'

export default function Claim(): JSX.Element {
  const { projects, loadingFailed } = useProjects()

  const { showMessage } = useMessageBanner()
  const [project, setProject] = useState<string>('none')
  const [token, setToken] = useState<string>('')

  const [projectMissing, setProjectMissing] = useState<boolean | null>(null)

  document.title = 'Claim Token | docat'

  const claim = async (): Promise<void> => {
    if (project == null || project === '' || project === 'none') {
      setProjectMissing(true)
      return
    }

    try {
      const response = await ProjectRepository.claim(project)
      setToken(response.token)
    } catch (e) {
      console.error(e)
      showMessage({
        content: (e as { message: string }).message,
        type: 'error',
        showMs: 6000
      })
    }
  }

  /**
   * Returns loaded project names for DataSelect
   * @returns project names as string[] or an empty array
   */
  const getProjects = (): string[] => {
    if (loadingFailed || projects == null) {
      return []
    }

    return projects.map((project) => project.name)
  }

  const onProjectSelect = (p: string): void => {
    if (p == null || p === '' || p === 'none') {
      setProjectMissing(true)
    } else {
      setProjectMissing(false)
    }

    setProject(p)
    setToken('')
  }

  return (
    <PageLayout
      title="Claim Token"
      description="Please make sure to store this token safely, as only one token can be generated per project and you will not be able to claim it again."
    >
      <StyledForm>
        <DataSelect
          emptyMessage="Please select a Project"
          label="Project"
          values={getProjects()}
          onChange={onProjectSelect}
          value={project ?? 'none'}
          errorMsg={
            projectMissing === true ? 'Please select a Project' : undefined
          }
        />

        {token !== '' ? (
          <TextField
            fullWidth
            label="Token"
            inputProps={{
              readOnly: true
            }}
            value={token}
          >
            {token}
          </TextField>
        ) : (
          <></>
        )}

        <button
          type="submit"
          disabled={token !== ''}
          onClick={() => {
            ;(async () => {
              await claim()
            })().catch((e) => {
              console.error(e)
            })
          }}
        >
          Claim
        </button>
      </StyledForm>
    </PageLayout>
  )
}
