// new-web/src/pages/Claim.tsx
import { TextField } from "@mui/material";
import { useState } from "react";
import DataSelect from "../components/DataSelect";
import PageLayout from "../components/PageLayout";
import StyledForm from "../components/StyledForm";
import ProjectRepository from "../repositories/ProjectRepository";
import LoadingPage from "./LoadingPage";

export default function Claim(): JSX.Element {
  const [loading, setLoading] = useState<boolean>(false);
  const [projectMissing, setProjectMissing] = useState<boolean | null>(null);
  const [errorMsg, setErrorMsg] = useState<string>("");
  const [project, setProject] = useState<string>("none");
  const [token, setToken] = useState<string>("");

  document.title = "Claim Token | docat";

  async function claim(): Promise<void> {
    if (!project || project === "none") {
      setProjectMissing(true);
      return;
    }

    setLoading(true);
    setErrorMsg("");

    try {
      const response = await ProjectRepository.claim(project);
      setToken(response.token);
    } catch (e: any) {
      console.error(e);
      setErrorMsg(e.message);
    } finally {
      setLoading(false);
    }
  }

  if (loading) {
    return <LoadingPage />;
  }

  return (
    <PageLayout
      errorMsg={errorMsg}
      title="Claim Token"
      description="Please make sure to store this token safely, as only one token can be generated per project and you will not be able to claim it again."
    >
      <StyledForm>
        <DataSelect
          emptyMessage="Please select a Project"
          label="Project"
          dataSource={ProjectRepository.get()}
          onChange={(p) => {
            if (p === "none" || !p) {
              setProjectMissing(true);
            } else {
              setProjectMissing(false);
            }

            setProject(p);
          }}
          value={project || "none"}
          errorMsg={projectMissing ? "Please select a Project" : undefined}
        />

        {(token && (
          <TextField
            fullWidth
            label="Token"
            inputProps={{
              readOnly: true,
            }}
            value={token}
          >
            {token}
          </TextField>
        )) || <></>}

        <button type="submit" onClick={claim}>
          Claim
        </button>
      </StyledForm>
    </PageLayout>
  );
}

// web/src/pages/Claim.vue
<template>
   <Layout>
    <form novalidate class="claim-form">
      <h1 class="claim-title">Claim Token</h1>
      <p>
        Please make sure to store this token safely, as only one token can be generated per project
        and you will not be able to claim it again.
      </p>


      <md-field>
        <label>Projectname</label>
        <md-select type="text" id="project" name="project" v-model="form.project" :disabled="sending" >
          <md-option
            v-for="project of projects"
            v-bind:key="project"
            :value="project"
          >
            {{ project }}
          </md-option>
        </md-select>
      </md-field>

      <md-field v-if="form.token">
        <label>Token</label>
        <md-input id="token" name="token" v-model="form.token" readonly />
      </md-field>

      <md-progress-bar md-mode="indeterminate" class="md-accent" v-if="sending" />
      <md-button class="md-button md-raised md-primary" :disabled="sending" @click="claim">Claim</md-button>

      <md-snackbar md-position="left" :md-duration="4000" :md-active.sync="showError" md-persistent>
        <span>{{ error }}</span>
        <md-button class="md-primary" @click="showError = false">Close</md-button>
      </md-snackbar>
    </form>
  </Layout>
</template>

<script>
import { validationMixin } from 'vuelidate'
import { required } from 'vuelidate/lib/validators'

import Layout from '@/components/Layout.vue'
import ProjectRepository from '@/repositories/ProjectRepository'

export default {
  name: 'Claim',
  mixins: [validationMixin],
  components: {
    Layout,
  },
  data() {
    return {
      form: {
        token: '',
        project: ''
      },
      projects: [],
      sending: false,
      error: '',
    }
  },
  async created() {
    document.title = "Claim Token | docat"
    this.projects = (await ProjectRepository.get())
  },
  validations: {
    form: {
      project: { required }
    }
  },
  methods: {
    async claim() {
      this.sending = true

      try {
        const msg = await ProjectRepository.claim(this.form.project)
        this.form.token = msg.token
      } catch(err) {
        // something went wrong while
        this.showError = true
        this.error = err
      }

      this.sending = false
    }
  }
}
</script>

<style scoped>
.claim-title {
  margin-bottom: 16px;
}

.claim-form {
  margin-top: 48px;
  padding-right: 16px;
  padding-left: 16px;
}
</style>
