// web/src/components/Project.vue
<template>
  <router-link :to="`/${project}/${latestVersion}`">
    <md-card>
      <md-card-header>
        <md-avatar>
          <img :alt="`${project} project logo`" :src="logoURL" />
        </md-avatar>

        <div class="md-title">{{ project }}</div>
        <div class="md-subhead">{{ versions.length }} Versions </div>
      </md-card-header>
    </md-card>
  </router-link>
</template>

<script>
import ProjectRepository from '@/repositories/ProjectRepository'

export default {
  name: 'Project',
  props: {
    project: String
  },
  data() {
    return {
      logoURL: '',
      latestVersion: '',
      versions: [],
    }
  },
  async created() {
    this.logoURL = ProjectRepository.getProjectLogoURL(this.project)
    this.versions = await ProjectRepository.getVersions(this.project)
    this.latestVersion = (this.versions.find((version) => version.name == 'latest') || this.versions[0]).name
  }
}
</script>

// web/src/components/Project.tsx
import React from 'react'
import ReactTooltip from 'react-tooltip'
import { Link } from 'react-router-dom'
import ProjectRepository from '../repositories/ProjectRepository'
import styles from './../style/components/Project.module.css'
import { Project as ProjectType } from '../models/ProjectsResponse'

import FavoriteStar from './FavoriteStar'

interface Props {
  project: ProjectType
  onFavoriteChanged: () => void
}

export default function Project(props: Props): JSX.Element {
  return (
    <div className={styles['project-card']}>
      <ReactTooltip />
      <div className={styles['project-card-header']}>
        <Link to={`/${props.project.name}/latest`}>
          {props.project.logo
            ? (
            <>
              <img
                className={styles['project-logo']}
                src={ProjectRepository.getProjectLogoURL(props.project.name)}
                alt={`${props.project.name} project logo`}
              />

              <div
                className={styles['project-card-title-with-logo']}
                data-tip={props.project.name}
              >
                {props.project.name}
              </div>
            </>
              )
            : (
            <div
              className={styles['project-card-title']}
              data-tip={props.project.name}
            >
              {props.project.name}
            </div>
              )}
        </Link>
        <FavoriteStar
          projectName={props.project.name}
          onFavoriteChanged={props.onFavoriteChanged}
        />
      </div>
      <div className={styles.subhead}>
        {props.project.versions.length === 1
          ? `${props.project.versions.length} version`
          : `${props.project.versions.length} versions`}
      </div>
    </div>
  )
}
